name: cicd

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ lazydl, standalone ]
        os: [ ubuntu, alpine ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: runmymind/docker-android-sdk
          flavor: |
            latest=auto
            prefix=${{ matrix.os }}-
            suffix=-${{ matrix.flavor }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag                    
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          file: ./${{ matrix.os }}/${{ matrix.flavor }}/Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: runmymind/docker-android-sdk/cache
          kaniko-args: |
            --use-new-run 
            --cleanup 
            --compressed-caching=false
